scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 20s
    metrics_path: /api/metrics
    static_configs:
      - targets: ["api:3000"]
        labels:
          service: "api-default"
          group: "api"
          name: "api-default"

  - job_name: "node-exporter"
    scrape_interval: 10s
    static_configs:
      - targets: ["node_exporter:9100"]

  - job_name: "postgresql"
    scrape_interval: 20s
    static_configs:
      - targets: ["postgres_exporter:9187"]
