FROM nginx:alpine

COPY ./nginx/entrypoint.sh /

RUN set -ex && \
	apk add --no-cache bash && \
	chmod +x /entrypoint.sh

COPY ./nginx/vhost.template /etc/nginx/conf.d/vhost.template

CMD ["/entrypoint.sh"]