name: Lint

on: push

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      # ESLint and Prettier must be in `package.json`
      - name: Install API Node.js dependencies
        run: npm install
        working-directory: api

      - name: Install Frontend Node.js dependencies
        run: npm install
        working-directory: frontend

      - name: Run API linter
        uses: samuelmeuli/lint-action@v1
        # working-directory: api
        with:
          github_token: ${{ secrets.github_token }}
          # Enable linters
          eslint: true
          # prettier: true
          eslint_dir: api/
          auto_fix: true

      - name: Run Frontend linter
        uses: samuelmeuli/lint-action@v1
        # working-directory: frontend
        with:
          github_token: ${{ secrets.github_token }}
          # Enable linters
          eslint: true
          # prettier: true
          eslint_dir: frontend/
          auto_fix: true
